export const GRAPH = {
  nodes: [
    "EQ1", "EQ2a", "EQ2b", "EQ3", "DISC1",
    "COMP1", "COMP2", "COMP3", "COMP4",
    "DISC2",
    "SYM1a", "SYM1b",
    "SYM2",
    "SYM3a", "SYM3b",
  ],
  edges: [
    ["EQ1", "EQ2a"],
    ["EQ1", "EQ2b"],
    ["EQ2a", "EQ3"],
    ["EQ2b", "EQ3"],
    ["EQ3", "DISC1"],
    ["EQ3", "COMP1"],
    ["COMP1", "COMP2"],
    ["COMP2", "COMP3"],
    ["COMP3", "COMP4"],
    ["DISC1", "DISC2"],
    ["COMP4", "DISC2"],
    ["DISC2", "SYM1a"],
    ["DISC2", "SYM1b"],
    ["SYM1a", "SYM2"],
    ["SYM1b", "SYM2"],
    ["SYM2", "SYM3a"],
    ["SYM2", "SYM3b"],
  ] as [string, string][],
};

export const NODE_LABELS: Record<string, string> = {
  anchor: "3.OA.A.3 — Multiplication/division word problems with equal groups, arrays, and measurement quantities",
  EQ1: "Compute with visual + told equivalence",
  EQ2a: "Infer equivalence from visual",
  EQ2b: "Compute without visual, told equivalence",
  EQ3: "Generate 'times as many' equivalence unprompted",
  DISC1: "Identify multiplicative vs additive language",
  COMP1: "Solve 'times as many' with hint",
  COMP2: "Solve 'times as many' independently",
  COMP3: "Identify multiplier from two given quantities",
  COMP4: "Solve 'times as many,' reference unknown (division)",
  DISC2: "Discriminate and compute additive vs multiplicative",
  SYM1a: "Read familiar equation as comparison",
  SYM1b: "Confirm comparison survives equation-form change",
  SYM2: "Read product-on-left equation as comparison",
  SYM3a: "Generate equation from verbal comparison",
  SYM3b: "Read one equation as two comparisons",
  target: "4.OA.A.1 — Interpret a multiplication equation as a comparison (e.g., 35 = 5 × 7 as '35 is 5 times as many as 7')",
};
